### ISSUE TITLE
does not work with anki 23.10.1

### ISSUE THREAD

**Issue by salmanuc** [sameerdash2/custom-stats-range#3]
debug info

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-02 21:19:48

When loading Custom Stats Range:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Salman\AppData\Roaming\Anki2\addons21\84374528\__init__.py", line 1, in <module>
    from . import custom_stats_range
  File "C:\Users\Salman\AppData\Roaming\Anki2\addons21\84374528\custom_stats_range.py", line 8, in <module>
    from PyQt5 import QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by sameerdash2** [comment]
Oh, looks like Anki is numbering versions based on year/month now. I thought I'd somehow missed 21 major version updates in one year, lol.

Anyway, I'm poking around and this seems to be just a matter of changing import statements. Should have a fix out soon (hopefully supporting both Qt5 and Qt6) 👍

**Comment by sameerdash2** [comment]
Fixed in 1.2.0
